{"trial_id": "00", "hyperparameters": {"space": [], "values": {}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/root/miniconda3/envs/pycaret/lib/python3.8/site-packages/keras_tuner/engine/base_tuner.py\", line 266, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/root/miniconda3/envs/pycaret/lib/python3.8/site-packages/keras_tuner/engine/base_tuner.py\", line 253, in _run_and_update_trial\n    self.oracle.update_trial(\n  File \"/root/miniconda3/envs/pycaret/lib/python3.8/site-packages/keras_tuner/engine/oracle.py\", line 108, in wrapped_func\n    ret_val = func(*args, **kwargs)\n  File \"/root/miniconda3/envs/pycaret/lib/python3.8/site-packages/keras_tuner/engine/oracle.py\", line 365, in update_trial\n    self._check_objective_found(metrics)\n  File \"/root/miniconda3/envs/pycaret/lib/python3.8/site-packages/keras_tuner/engine/oracle.py\", line 623, in _check_objective_found\n    raise ValueError(\nValueError: Objective value missing in metrics reported to the Oracle, expected: ['val_accuracy'], found: dict_keys([])\n"}